---
- name: error handling on the  servers
  hosts: node1
  tasks:
    - block:
      - name: uninstall git on node1
        apt:
          name: "{{item.a}}"
          state: "{{item.b}}"
          update_cache: yes
        with_items:
          - {a: git,b: absent}
      rescue:
        - name: install git on redhat server
          yum:
            name: maven
            state: present
- name: install on yum modling
  hosts: node2
  tasks:
    - block:
      - name: uninstall tree
        yum:
          name: tree
          state: present
      always:
        - name: display success
          debug:
            msg: "git done massage"
...      
