---
- name: Create users and copy files inot users home dir
  hosts: all
  tasks:
    - name: Create multiple users
      user:
        name: "{{item.a}}"
        password: "{{item.b}}"
        home: "{{item.c}}"
      with_items:
        - {a: sunny,b: intelliqit,c: /home/sunny}
        - {a: sarika,b: intelliqit,c: /temp/sarika}
    - name: Copy files inot users home dirs
      copy:
        src: "{{item.a}}"
        dest: "{{item.b}}"
      with_items:
        - {a: /etc/passwd,b: /home/sunny}
        - {a: /etc/group,b: /temp/sarika}
...
