---
- name: Install,uninstall,upgrade s/w applications
  hosts: all
  tasks:
    - name: Install/uninstall sw's
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
      with_items:
        - {a: tree,b: present}
        - {a: git,b: absent}
        - {a: maven,b: latest}
        - {a: firewalld,b: absent} 
...
