---
- name: Delete the file if it is empty
  hosts: all
  tasks:
    - name:     Capture file info
      stat:
        path: /tmp/file200
      register: results
    - name: Display output of the above module
      debug:
        var: results
    - name: delete if the file is emply
      file:
        name: /temp/file200
        state: absent
      when: results.stat.size == 0
