---
- name: Create users and copy files inot users home dir
  hosts: all
  tasks:
    - name: Create multiple users
      user:
        name: "{{item.a}}"
        password: "{{item.b}}"
        home: "{{item.c}}"
      with_items:
        - {a: Ravi,b: intelliqit,c: /home/Ravi}
        - {a: Anu,b: intelliqit,c: /tmp/Anu}
    - name: Copy files inot users home dirs
      copy:
        src: "{{item.a}}"
        dest: "{{item.b}}"
      with_items:
        - {a: /etc/passwd,b: /home/Ravi}
        - {a: /etc/group,b: /tmp/Anu}
...
